services:
  boardgames-planner:
    build: .
    container_name: boardgames-planner
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    environment:
      TRUST_PROXY: 1
      DEFAULT_LANG: ''
      #ADMIN_PASSWORD: admin
      LOGIN_RETRY_DELAY: 10
      #MYLUDO_PROFILE: https://www.myludo.fr/#!/profil/[...]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
