services:
  boardgames-planner:
    build: .
    container_name: boardgames-planner
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    environment:
      ADMIN_PASSWORD: admin
      LOGIN_RETRY_DELAY: 10
      #MYLUDO_PROFILE: https://www.myludo.fr/#!/profil/[...]
      #WHATSAPP_MAIN: https://chat.whatsapp.com/[...]
      #WHATSAPP_MJC: https://chat.whatsapp.com/[...]
    restart: unless-stopped
